# Generated by Django 5.1.1 on 2025-06-14 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_professor_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=90)),
                ('birth_date', models.DateField()),
                ('postcode', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('department', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol'), ('Boshqa', 'Boshqa')], max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='add_course_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('duration', models.CharField(max_length=100)),
                ('course_price', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('department', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('year', models.CharField(max_length=100)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.add_professor_model')),
            ],
        ),
    ]
