# Generated by Django 5.1.1 on 2025-06-14 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_add_course_model_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_student_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=90)),
                ('birth_date', models.CharField(max_length=90)),
                ('postcode', models.IntegerField()),
                ('description', models.TextField()),
                ('gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol'), ('Boshqa', 'Boshqa')], max_length=90)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.add_course_model')),
            ],
        ),
    ]
