# Generated by Django 5.1.1 on 2025-06-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_add_student_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_professor_model',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='add_student_model',
            name='postcode',
        ),
    ]
