# Generated by Django 5.1.1 on 2025-06-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_profileuser_address_profileuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
