# Generated by Django 5.1.1 on 2025-06-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_course_model',
            name='days',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
